export const NEWLINE = "\n"
// export const NEWLINE = "\r\n"
export const MENU_NAME = "tcd"
export const FOLDER_NAME = "tcd-apps-script-output"
export const FOLDER_ID = "1Vhw0UvGogfuhTko2Bc9Dql807_YB3uHn"
